---
#   __  __ _  ___   ___        __
#  |  \/  | |/ / \ | \ \      / /
#  | |\/| | ' /|  \| |\ \ /\ / / 
#  | |  | | . \| |\  | \ V  V /  
#  |_|  |_|_|\_\_| \_|  \_/\_/   
                                
# Config file of MaharliKraft Hub

# If you're having problems with this plugin, Contact dpg#2396

# Lobby
world: "newhub"

# Messages when a player triggered a command:
title: "Teleported"
subtitle: "To Lobby!"
message-to-player: "You have been teleported!"
console-error: "Use this ingame"

# © MaharliKraft Network 2020-2022 | All Rights Reserved
---
