name: InstaHub
version: 2.2.0
main: DPGD896\Hub\Main
api: 4.0.0
author: DENPlayz414502

commands:
  hub:
    usage: /hub
    description: §l§1Maharli§4Kraft §eMain Lobby
    permission: mk.hub
    
permissions:
  mk.hub:
    description: MaharliKraft Hub
    default: true
