name: MaharliKraft-Hub
version: 2.0
main: DPGD896/Hub/Main
api: 4.0.0
author: DENPlayz414502

commands:
  hub:
    usage: /hub
    description: §l§1Maharli§4Kraft §eMain Lobby!
    permission: maharlikraft.hub
    
permissions:
  maharlikraft.hub:
    description: MaharliKraft Hub
    default: true
